# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateNewEmptySpeciesShapeFile
                                 A QGIS plugin
 Create a new empty Species Shape File
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-31
        copyright            : (C) 2023 by NM BioPark Society
        email                : www.bioparksociety.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateNewEmptySpeciesShapeFile class from file CreateNewEmptySpeciesShapeFile.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .new_empty_shape_file import CreateNewEmptySpeciesShapeFile
    return CreateNewEmptySpeciesShapeFile(iface)
