# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MultipleShapeFile
                                 A QGIS plugin
 Creates multiple shape file from the list
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-17
        copyright            : (C) 2023 by Kritim Bastola
        email                : kritimbastola2005@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MultipleShapeFile class from file MultipleShapeFile.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Multiple_Shape_File import MultipleShapeFile
    return MultipleShapeFile(iface)
